def check(game):
    n = len(game)
    if n < 2:
        if '_' not in game:
            return False
        return True
    if game[0] != '_' and game[0] != game[1]:
        return False
    for i in range(1,n-1):
        if game[i] != '_' and game[i] != game[i-1] and game[i] != game[i+1]:
            return False
    if game[n-1] != '_' and game[n-1] != game[n-2]:
        return False
    return True

def ladybug(inp):
    lines = inp.split('\n')
    games = []
    print (lines)
    lines = [x for x in lines if x != '']
    for i in range(1,len(lines),2):
        games.append([x for x in lines[i+1]])
    for game in games:
        print(check_game(game))

def check_game(game):
    if game.count('_') == 0:
        if check(game):
            return "YES"
        else:
            return "NO"
    checked = ['_']
    for i in game:
        if i not in checked:
            if game.count(i) == 1:
                return "NO"
            checked.append(i)
    return "YES"



inp = '''
38\n80\n_FWYSSENEDBO_KSEVUAB_WZ_GASASVEVS_O_NSVBYFNADE_WWVSBKAE_F_VAS_F_AAAEWBE_WEAEOAYV\n50\nZBF_MIFUXJNQGQRFZVRQUFFFFNGFIBJ_XZVIRFGMJRJFVMNJMF
\n30
\nYFCA_NXMGJYYGCMMGGGXYNAMFNJJX_
\n34
\nCBLJUKUWSTIIUKUBQSITSULTJKCUSKBCKB
\n21
\nA_TOJRPRW__JOJP__WAJT
\n70
\nE__TZJTD_OYGFM__QKZD_LJL_TJ_YED__DETFFYGJQ_T_JJZDJFMQO___T_JTQGKDTT_ET
\n61
\n_PMBBIK_THVEQPN_RHSUP__BI_R_HP_PTEHPRHBKVBN_SQKNB_NVRB_PMBUNT
\n39
\nQ_ZEUKWDG_Q_VEE_Z_PDDDEEP_PVDVVGZUEU_Q_
\n90
\n__MY_T_C_FY_USSALD_U_AIEJRPVNUA_TI_CAYTE__EPI_FDLMA_U_CC_AAUAVNUSJYAUD_AP_CIA_D_E__TAUSU_N
\n89
\nLXA__KNR_R___CJJLF_IJPFLRM__V_FAAN_JU__RJ__RFMJ_PP_L__R_RR___AJLJ_LKIAP_LX___L_FACFJXRC_L
\n99
\nI_S_AHBBZJLQDKQZXIG_TOC_BGQMQVTEWAAWIBL_MKJQQGSZIBWSQQ__K_HEHZZZG_BBCEJOWIGCGQTBQ_Z_DHGAIQ_____LVA_
\n18
\nOADXPZXDAXXPDOPBPB
\n5
\nIIIAA
\n51
\nP_QUVFTC_T_A_ST_Y__T_AQ_TTTYATTIAYUUV_U_TPP_A_T_AFT
\n85
\nVAKZIIPDVVKT__BWMY_IQFNXRZR_FTZKDNMVZRMRP_IFFFPKKRWBBXTVVZKTAV_RRKKV__I__MB_K_KVYVMIP
\n76
\n_YYYDC_P_B_RBNW_QKVD_EVXZQVYEYRVCY_EXVYYNY_Z_BVBVE_ZXZ_DBBVYB_BWVR_X_YRB___B
\n58
\nBWDXDZUXXVSH_MLOIC_SDXDIBDDHBUCBS_D_WZHMDWSX_DMZVD_MHX_LB_
\n29
\n__B_MODTKB__DM__BOB__VBVMD_OB
\n31
\nMZSVIFE_CZSSI_EESIMSZZEMZMIICCF
\n99
\n_ELSXLM_Z_RZBOBMEIABC_VZQ_X__RSXWW__BZZMMXZW_C__RV__EB_S_VEIEX_IR__AWBSRXOCXE_B_X__Z__SXC_AZCC_OABS
\n91
\nWKQPNY_MJTQ_V_YEO__PXICOB_TPKK_P_MQQOPYP_NVNIPYYIQVPPYEXSY_Y_K_YQJQYWQ_POY__P_PEQITKQBYPIQE
\n88
\nE_LBAI_YCXSF_GQL_PHTXLQOWXBBEYBLXBXLQLEBBGSLFYBCQFIE_XX_LX_B_BSPQXSOTQQLP_QP_QP__BFCSSBT
\n61
\nRHLP_KS_HADGELHPE_FCKEPHF_HHGRHHXXLFHEXCFR_XKDPPH_CPGGEDK_E_P
\n97
\nKWNGPWHQDVSXICSPE_OJQSBLKOERBR_GSBENDPBKOGJPPQCEXG_BRKGCP_KW_HWIN_KLOWROPREKHEWRWHEQSQ_RXSBJIBESS
\n72
\nL_OTJQXNPRHL_MLQQC_HTQDNNPQ_PCTJHQQ_M_DLHKT_NCXH_TLQLCH_Q_POTMORQLTQR_HM
\n15
\nPHMWXXPWWXWWXHW
\n35
\nZF__KSHMNOILMFIMFHFM_ZNIMLFHLNOLZNM
\n16
\nXRLSCLXCXSSSSLXX
\n24
\n_F_FDZ_KK_D_ZZFF__FFKK_Z
\n34
\nDMMQ___KOKOOL_KMD_OMMM__M_DOQ_K_QK
\n23
\nAGUPF__PGFP_AFKGFUFUAP_
\n43
\nGY_KGOFTBLOZRSGGZOFTTBFTFTBZ_Y_ORYLZOGGSLTF
\n81
\nA_E_W_UMARGHHGUPASDKYRF_URHYEFURYA_F_HHHD__HARREASEY__A__UADHKURFSRRM_GGAAM_SRHRP\n37\nN_JG__XYED_RXHRX_J_XNXGDYDE_GJ_E__H_X\n91\nFVIVAZ_QDZRPICRMUPZWGDAEEI_I_WZQZWGMZP_IIIPEUCVRZWAZIIZEQIIIDCP_AAZZPWRIGWWAAR_DFUDZZ_V_MWZ\n16\nKTXODXKXDXXDDOXX\n25\nCZCYAV_ICVCYCCIDDZID_AAZC\n55\n__XWTZXUWVT__H_PUGHZ_G___H_GZWTTWGZ_XHHZWGXZWGPV_U_UWXV
'''
ladybug(inp)
